### ISSUE TITLE
Update helm chart install commands in chart README

### ISSUE THREAD

**Issue by akijakya** [bank-vaults/vault-helm-chart#14]
With the new OCI images we need something like this: `helm upgrade --install --wait vault oci://ghcr.io/bank-vaults/helm-charts/vault`. This won't work with the current version however, we need to upgrade the unsealer image tag to 1.20.4 and tag a new version of the chart!

**Comment by ramizpolic** [comment]
https://github.com/bank-vaults/vault-helm-chart/blob/main/vault/README.md
