### ISSUE TITLE
add Enterprise License in Vault

### ISSUE THREAD

**Issue by anhbt1005** [bank-vaults/vault-helm-chart#144]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-helm-chart/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Problem Description

I haven't seen the way to enable enterprise license for Vault.
Can bank-vault implement this feature?

### Proposed Solution

As vault-helm repository indicates, can we implement this feature to enable enterprise license?
- Mounts an existing secret to /vault/license and sets VAULT_LICENSE_PATH appropriately.
- Sets up its license on startup

**Comment by ramizpolic** [comment]
Hey @anhbt1005 , you should be able to support this behaviour by specifying custom `vault.customSecrets` and `vault. envSecrets` Chart values.
