### ISSUE TITLE
Multiple storage blocks generated in config.json

### ISSUE THREAD

**Issue by MuriukiPM** [bank-vaults/vault-helm-chart#180]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-helm-chart/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Vault Helm Chart Version

1.20.3

### Kubernetes Version

1.30

### Kubernetes Distribution/Provisioner

EKS

### Expected Behavior

Deploying the chart with custom values for `vault.config.storage` should not generate a config.json with two storage blocks:

Values file
```yaml
vault:
  vault:
    config: 
      storage:
        dynamodb:
          ha_enabled: true
          region: us-east-1
          table: "vault-backend"
...
```

Expected config json:
```json
{
  "api_addr": "http://127.0.0.0:8200",
  "storage": {
    "dynamodb": {
      "ha_enabled": true,
      "region": "us-east-1",
      "table": "vault-backend"
    }
  },
  "telemetry": {
    "statsd_address": "localhost:9125"
  },
  "ui": true
}
```

### Actual Behavior

Two storage blocks are added to the config.json

Generated config json:
```json
{
  "api_addr": "http://127.0.0.0:8200",
  "storage": {
    "dynamodb": {
      "ha_enabled": true,
      "region": "us-east-1",
      "table": "vault-backend"
    },
    "file": {
      "path": "/vault/file"
    }
  },
  "telemetry": {
    "statsd_address": "localhost:9125"
  },
  "ui": true
}
```

This causes an error in the vault container since there is more than one storage block
`error loading configuration from /vault/config/config.json: error parsing 'storage': only one "storage" block is permitted`

### Additional Information

The storage block for `file` seems to be from [values.yaml#L194](https://github.com/bank-vaults/vault-helm-chart/blob/498b7d848a351368ca36fb3895a96bb08f123903/vault/values.yaml#L194), previously this was set to `{}`. This was reverted in [PR#103](https://github.com/bank-vaults/vault-helm-chart/pull/103)

**Comment by florindragos** [comment]
also having this issue. is there any workaround?

**Comment by sazzle2611** [comment]
We also have this issue after switching to this chart from the banzaicloud chart (because their domain has been down for ages). We use mysql storage.

Generated config:
```
{
  "api_addr": "http://127.0.0.1:8200",
  "disable_mlock": false,
  "listener": {
    "tcp": {
      "address": "[::]:8200",
      "tls_cert_file": "/vault/tls/server.crt",
      "tls_disable": true,
      "tls_key_file": "/vault/tls/server.key"
    }
  },
  "storage": {
    "file": {
      "path": "/vault/file"
    },
    "mysql": {
      "address": "pxc.database.svc.cluster.local:3306",
      "password": "<redacted>",
      "username": "vault"
    }
  },
  "telemetry": {
    "statsd_address": "localhost:9125"
  },
  "ui": true
}```
